[build]
  functions = "netlify/functions"  # Adjust if your functions folder is in a different location

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/getCities"
  status = 200
  force = true
